version: 2
jobs:
  build:
    docker:
    - image: circleci/android:api-28-alpha
    steps:
    - checkout
    - run:
        name: Download Dependencies
        command: ./gradlew dependencies
    - run:
        name: Build Project
        command: ./gradlew :app:assembleDebug
    - run:
        name: Run ktlint
        command: ./gradlew ktlint
    - run:
        name: Run Tests
        command: ./gradlew test
    - store_test_results:
        path: app/build/test-results