version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run:
          name: Build Project
          command: ./gradlew :app:assembleDebug
      - run:
          name: Run Tests
          command: ./gradlew test